### ISSUE TITLE
Unit tests make API calls

### ISSUE THREAD

**Issue by Jamesking56** [JustSteveKing/LaravelPostcodes#12]
## Detailed description

`PostcodeServiceTest` seems to make actual API calls, which is a bad practice for unit tests. We shouldn't need to hit an external API to test the project.

## Context

If, for example, I wanted to run the unit tests offline, I can't because that test requires external access. Same for if the API went down.

## Possible implementation

Create a mock for Guzzle client that responds in the same way the API would and give that to `PostcodeService`

## Your environment

Irrelevant

**Comment by JustSteveKing** [comment]
@Jamesking56 I agree! Open to PR's on this one 😄 I even added the hacktoberfest label!

**Comment by Jamesking56** [comment]
I might have a go at a PR later @JustSteveKing :+1:
