### ISSUE TITLE
Make tests more stringent

### ISSUE THREAD

**Issue by kayrunm** [JustSteveKing/LaravelPostcodes#17]
## Detailed description

Given that the tests don't actually make a request to the API—and I'm not suggesting they should, for what it's worth—it might be a good idea to make the tests a bit more stringent.

## Context

It can be easy to add a new feature and add a typo to the endpoint without realising, and the tests would never be able to flag up an issue with it.

## Possible implementation

In a package that I've created before, I make sure that the request URI also matches an expectation, by storing the last request (`$this->lastRequest = $mock->getLastRequest()`)

```php
public function testServiceCanGetPostcode()
{
    $service = $this->service(200, json_encode(['reuslt' => ['postcode' => $this->postcode]]));
    $result = $service->getPostcode($this->postcode);

    $this->assertEquals($result->postcode, $this->postcode);
    $this->assertEquals('postcode/N11 1QZ', (string) $this->lastRequest->getUri());
}
```

**Comment by JustSteveKing** [comment]
I am open to this, I did do actual implementation tests originally when I first published. Others suggested mocking and submitted a PR. If the test harness were to be improved I would not complain, as long as that didn't introduce brittle tests.

**Comment by kayrunm** [comment]
I’ll open a PR with my suggestions and you can see what you think
