### ISSUE TITLE
Convert all returns to return Collection instead off Array where appropriate

### ISSUE THREAD

**Issue by mikhailkozlov** [JustSteveKing/LaravelPostcodes#28]
## Detailed description

Looks like some of the functions return Laravel Collection and others return array or null if multiple results are returned. I propose we use one or another for consistency. 

## Context

Reasoning for moving to collections: 
- It is Laravel package and Collection is what most of API returns 
- Collections are easier to use
- Collection can handle null response without braking code that uses Collection

## Possible implementation

Turn:
```
    public function autocomplete(string $partialPostcode): ?array
    {
        return $this->getResponse("postcodes/$partialPostcode/autocomplete");
    }

````
Into 
```
    public function autocomplete(string $partialPostcode): object
    {
        return collect($this->getResponse("postcodes/$partialPostcode/autocomplete"));
    }
```

**Comment by JustSteveKing** [comment]
We will also want to make we have the correct return type on this method
