### ISSUE TITLE
Is it possible to move the logic into a Request?

### ISSUE THREAD

**Issue by ejntaylor** [JustSteveKing/LaravelPostcodes#35]
Working well with the following in my controller:

        //validate postcode first
        $service = resolve(PostcodeService::class);
        $this->validate($request, [
            'site_postcode' => [
                'required',
                'string',
                new Postcode($service),
            ],
        ]);

I'm trying to follow best practice and keep my request validation in a separate Request file, which i I call in my store method with dependency injection. Eg:     

    public function store(StoreProjectRequest $request) { ... }

Is there a good practice here for me to move the Postcode validation into this Request? Perhaps as a rule or as a separate function? Advice appreciated - thanks 👍

**Comment by JustSteveKing** [comment]
Hey @raisonon of course!

```php
public function rules()
{
    return [
        'site_postcode' => [
            'required',
            'string',
            Rule::postcode()
        ]
    ];
}
```

**Comment by ejntaylor** [comment]
Ah fantastic - I think the problem before was I didn't add this to my Request file:

use Illuminate\Validation\Rule;

Now it works using your code - Thanks again :)
