### ISSUE TITLE
Query builder problem with Laravel 8

### ISSUE THREAD

**Issue by m-popa** [JustSteveKing/LaravelPostcodes#39]
Hello and thanks for the awesome package!

I seem to have a problem with the query builder in Laravel 8.

I remember before it worked to search for a postcode as LE27HS or LE2 7HS, since the Laravel 8 upgrade it is only working if I search for it with proper formatting. Code below maybe you can have a suggestion for me.

Thanks,
Mihai

 

`        return $this->builder->whereHas('location', function ($query) use ($name) {
            $query->where('postcode', 'like', '%'.$name.'%')
                ->orWhere('city', $name)
                ->orWhere('region', $name);
        });`

**Comment by JustSteveKing** [comment]
I also noticed this change, I believe it's an API change unfortunately!
