### ISSUE TITLE
Add support for PHP 8

### ISSUE THREAD

**Issue by dushaun** [JustSteveKing/LaravelPostcodes#41]
Currently there is support for Laravel 8 in this package, but it doesn't support Laravel 8 running on PHP 8.

Whenever I am running composer commands, the platform requirement issues flash up.

A possible solution for this would be to add the `|8.0` next to the current PHP version present in the composer.json

**Comment by totov** [comment]
Looks like support for this was added in https://github.com/JustSteveKing/LaravelPostcodes/commit/68e6e5782d658efdde861b77ba61dcc657a31510 but a new release hasn't been tagged yet. @JustSteveKing any chance you could do that please?

**Comment by JustSteveKing** [comment]
Sorry, I must have forgotten to tag it! Here you go: https://github.com/JustSteveKing/LaravelPostcodes/releases/tag/V1.4.0
